[build]
command = "hugo --gc --minify -D -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.119.0"
TZ = "New York/USA"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"
